# Generated by Django 5.2.8 on 2025-11-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitcompletion',
            unique_together=set(),
        ),
    ]
