# Generated by Django 5.2.8 on 2025-11-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habitcompletion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitcompletion',
            unique_together={('habit', 'date')},
        ),
    ]
